### ISSUE TITLE
Bring RabbitMQCustomResource CRD validation in-line with current custom resource schema

### ISSUE THREAD

**Issue by bfink13** [indeedeng/rabbitmq-operator#16]
The validation in https://github.com/indeedeng/rabbitmq-operator/blob/master/examples/rabbitmq_operator.yaml#L22 is out of date. It should be updated to match the schemas that the POJOs expect.

The "root" of the spec is https://github.com/indeedeng/rabbitmq-operator/blob/master/rabbitmq-operator-model/src/main/java/com/indeed/operators/rabbitmq/model/crd/rabbitmq/RabbitMQCustomResourceSpec.java - from there the rest of the POJOs can be found.

**Comment by Reagankm** [comment]
Want to make sure I understand this.  Is the idea here to add/adjust the missing or misnamed properties of ClusterSpec, RabbitMQComputeResources, and RabbitMQStorageResources?

**Comment by Reagankm** [comment]
I'm going to give this a try
