### ISSUE TITLE
Add logging for API operations

### ISSUE THREAD

**Issue by bfink13** [indeedeng/rabbitmq-operator#40]
There is currently no logging when we execute a call against the management API. We should add some. If we can't figure out a good solution within the operator, maybe we can add it to https://github.com/indeedeng/rabbitmq-admin

**Comment by ghost** [comment]
I'd lean towards putting the logging in rabbitmq-admin.

**Comment by bfink13** [comment]
With https://github.com/indeedeng/rabbitmq-admin/issues/13 we'll be able to customize how we want this logging.
