### ISSUE TITLE
“kubectl delete pv -n rabbitmqs --all” too dangerous

### ISSUE THREAD

**Issue by cuijxin** [indeedeng/rabbitmq-operator#68]
In scripts/deploy-operator.sh

 "kubectl delete pv -n rabbitmqs --all" 

This command is too dangerous that it will delete all the pv objects in the cluster.

Now I am trying to recover the data that was deleted by mistake. Does anyone have a good idea？

**Comment by mjpitz** [comment]
@jhamacher-indeed : can your team take a look at this please?
