### ISSUE TITLE
Support creating virtual resources

### ISSUE THREAD

**Issue by mjpitz** [indeedeng/rabbitmq-operator#78]
Outside of clusters, it would also be nice to manage a few virtual resources in addition to the cluster alone. This would remove the need to give applications administrative access to the cluster. It would also let you declaratively manage your messaging topologies using kubernetes YAML.

Proposed virtual resources:
- Exchange
- ExchangeBinding
- Queue
- QueueBinding

**Comment by mjpitz** [comment]
Somewhat related: https://github.com/indeedeng/rabbitmq-operator/issues/79

**Comment by ghost** [comment]
Do you imagine the k8s YAML being the sole source of truth for these resources? I.e., should the operator remove any resources that are not present in the YAML?

**Comment by mjpitz** [comment]
I think you'd need to support a mix? Some older applications will probably have the logic baked into it while newer clients could benefit from a no code / low code approach by only providing the necessary exchange and queue configurations in their deployments.

The way I've typically seen this done is the processes that an operator is managing add a set of tags / labels that make it easy for them to see what virtual resources are their responsibility so that they don't delete any resources unintentionally. An example you might be able to follow is the kafka operator from banzai cloud: https://operatorhub.io/operator/banzaicloud-kafka-operator
