### ISSUE TITLE
Allow rabbitmq username and passwords to be specified

### ISSUE THREAD

**Issue by mjpitz** [indeedeng/rabbitmq-operator#80]
Right now, these are programmatically generated. It would be nice if we could provide username and passwords to the spec instead of just generating them.

**Comment by ghost** [comment]
Do you think the credentials should always be required to be provided, rather than generated?

**Comment by mjpitz** [comment]
Most operators I've seen let you do either or. i.e. if you don't provide an externalSecretRef, then one is generated for you. A lot of helm charts follow this pattern as well.
