### ISSUE TITLE
Allow special config files to be configured

### ISSUE THREAD

**Issue by mjpitz** [indeedeng/rabbitmq-operator#82]
Right now, there are a couple configurations that the operator treats as "global" configuration for all clusters. It would be great if these were configurable instead of the name being assumed.

**Comment by ghost** [comment]
Are you referring to the ConfigMaps that start at https://github.com/indeedeng/rabbitmq-operator/blob/master/examples/rabbitmq_operator.yaml#L262 in the example?

**Comment by mjpitz** [comment]
@amccormick-indeed : yup that would be the one
